name: release

on:
    push:
        branches:
            - main
        paths:
            - "*.js"
    workflow_dispatch:

jobs:
    release:
        env:
            NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        name: semantic-release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup node 18.16.0
              uses: actions/setup-node@v4
              with:
                  node-version: 18.16.0

            - name: npm install
              run: npm ci

            - name: Install semantic-release
              run: npm i -g semantic-release

            - name: Release
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: npx semantic-release
